version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn yourapp.wsgi:application -b 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
